from enum import Enum


class IngredientType(Enum):
    GRAIN = "GRAIN"
    FRUIT = "FRUIT"
    VEGETABLE = "VEGETABLE"
    DAIRY = 'DAIRY'
    OIL = 'OIL'
    MEAT = 'MEAT'
    MOLLUSK = 'MOLLUSK'
    FISH = 'FISH'
    EGG = 'EGG'
    CRUSTACEAN = 'CRUSTACEAN'
    LEGUME = 'LEGUME'
    NUTS_SEEDS = 'NUTS_SEEDS'
    SWEETENER = "SWEETENER"
    SPICE_HERBS = "SPICE_AND_HERBS"
    PANTRY_STAPLE = 'PANTRY_STAPLE'
    CONDIMENT = "CONDIMENT"
    CHOCOLATE = 'CHOCOLATE'
    BAKERY = 'BAKERY'
