export const ingredientTypes = {
    PANTRY_STAPLE: "Pantry Staples",
    GRAIN: "Grains",
    FRUIT: "Fruits",
    VEGETABLE: "Vegetables",
    OIL: "Oils",
    DAIRY: "Dairy",
    MEAT: "Meats",
    NUTS_SEEDS: "Nuts & Seeds",
    FISH: "Fish",
    LEGUME: "Legumes",
    EGG: "Eggs",
    CRUSTACEAN: "Crustaceans",
    MOLLUSK: "Molluscs",
    CHOCOLATE: "Chocolates",
    SPICE_HERBS: "Spice & Herbs",
    CONDIMENT: "Condiments",
    SWEETENER: "Sweetener",
    BAKERY: "Bakery",
};

export const INGREDIENT_TYPES = [
    "GRAIN",
    "FRUIT",
    "VEGETABLE",
    "DAIRY",
    "OIL",
    "MEAT",
    "MOLLUSK",
    "FISH",
    "EGG",
    "CRUSTACEAN",
    "LEGUME",
    "NUTS_SEEDS",
    "SWEETENER",
    "SPICE_HERBS",
    "PANTRY_STAPLE",
    "CONDIMENT",
    "CHOCOLATE",
    "BAKERY",
];
